package share.game.comunication;

public enum RequestType {
	ERRORMOVE, ENDMOVE, MOVESHEEP, MOVESHEPHERD, MOVEBUYFIELD, MOVEBLACKSHEEP, ACK, ENDMOVEPAY, NOTENOUGHMONEY, WAITFORYOURTURN, STARTGAME, KILL, COUPLING, TURNOF, STARTSYNC, ENDSYNC, STOPCOMEBACK, PLAYERBANNED;
}
